- name: Ensure SELinux is set to disabled mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Install Redis repo on CentOS-8
  ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y --skip-broken
  ignore_errors: true  

- name: Install Redis module
  ansible.builtin.shell: dnf module enable {{COMPONENT}}:remi-6.2 -y
  ignore_errors: true


- name: Install the  redis package
  ansible.builtin.yum:
    name: "{{COMPONENT}}"
    state: present

- name: Stop the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: stopped 
  ignore_errors: true      


- name: Replace loop back address 127.0.0.1 with 0.0.0.0 on Redis config 
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'  

- name: Enable and start the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: true    
    daemon_reload: yes     

- name: adding the user node_exporter to install promethus agent 
  ansible.builtin.shell: useradd -M -r -s /bin/false node_exporter
  ignore_errors: true 

- name: Remove existing files and folders 
  ansible.builtin.file:
    path: 
      - /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
      - /tmp/node_exporter-1.5.0.linux-amd64
    state: absent
  ignore_errors: true  


- name: Download node exporter files
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter tp bin
  ansible.builtin.copy:
    src:  /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: node_exporter
    group: node_exporter
    mode: '0777'    
    remote_src: yes