- name: Ensure SELinux is set to disabled mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Download mongodb repo file and place it a directory
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/{{COMPONENT}}/main/mongo.repo
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo


- name: Install the  MongoDB package
  ansible.builtin.yum:
    name: "{{COMPONENT}}-org"
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true    
    daemon_reload: yes    


- name: Replace loop back address 127.0.0.1 with 0.0.0.0 on MongoDB config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Restart the MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: restarted


- name: Recursively remove file
  ansible.builtin.file:
    path: /tmp/{{COMPONENT}}
    state: absent
    force: true 

- name: Recursively remove file
  ansible.builtin.file:
    path: /tmp/{{COMPONENT}}.zip
    state: absent
    force: true 


- name: Recursively remove directory
  ansible.builtin.file:
    path: /tmp/{{COMPONENT}}-main
    state: absent    
    force: true

- name: Download mongodb database file and place it a directory
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/{{COMPONENT}}.zip

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /tmp/
    remote_src: yes

- name: Load the DB into Mongo 
  ansible.builtin.shell: mongo < /tmp/{{COMPONENT}}-main/catalogue.js &&  mongo < /tmp/{{COMPONENT}}-main/users.js


- name: adding the user node_exporter to install promethus agent 
  ansible.builtin.shell: useradd -M -r -s /bin/false node_exporter
  ignore_errors: true 

- name: Remove existing files and folders 
  ansible.builtin.file:
    path: 
      - /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
      - /tmp/node_exporter-1.5.0.linux-amd64
    state: absent
  ignore_errors: true  


- name: Download node exporter files
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter tp bin
  ansible.builtin.copy:
    src:  /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: node_exporter
    group: node_exporter
    mode: '0777'    
    remote_src: yes

- name: Copy systemd file. 
  ansible.builtin.copy:
    src:  node_exporter.service
    dest: /etc/systemd/system/
    remote_src: yes
    

- name: Enable and start the service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true    
    daemon_reload: yes 

