#- name: Setting up frontend
 # hosts: frontend
  #become: true
  #roles:
 #  - frontend

#- name: Setting up cart
 # hosts: cart
  #become: true
  #roles:
  # - cart

#- name: Setting up catalogue
 # hosts: catalogue
 # become: true
 # roles:
 #  - catalogue

#- name: Setting up user
#  hosts: user
#  become: true
#  roles:
#   - user

#- name: Setting up redis
#  hosts: redis
#  become: true
#  roles:
#    - redis

#- name: Setting up mongodb
#  hosts: mongodb
#  become: true
#  roles:
#    - mongodb


- name: Setting up Rabbitmq
  hosts: rabbitmq
  become: true
  roles:
    - rabbitmq