#- name: Setting up frontend
 # hosts: frontend
  #become: true
  #roles:
 #  - frontend

- name: Setting up cart
  hosts: cart
  become: true
  roles:
   - cart
  ansible.builtin.include_vars: 
    file: mail.yml