#- name: Setting up frontend
 # hosts: frontend
  #become: true
  #roles:
 #  - frontend

#- name: Setting up cart
#  hosts: cart
#  become: true
#  roles:
#   - cart

- name: Setting up catalogue
  hosts: catalogue
  become: true
  roles:
   - catalogue
