- name: Install the  python package
  ansible.builtin.yum:
    name: 
     - python36
     - gcc
     - python3-devel
    state: present

- name: creating a roboshop user account 
  user:
    name: roboshop
  register: appuser
  ignore_errors: true 

- name: Download {{COMPONENT}} files
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/{{COMPONENT}}.zip

- name: Stop the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: stopped     

- name: Recursively remove file
  ansible.builtin.file:
    path: /home/roboshop/*
    state: absent
    force: true 

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /tmp/
    remote_src: yes

- name: Download NodeJS repo file and place it a directory
  ansible.builtin.shell: rm -rf /tmp/{{COMPONENT}} && mv /tmp/{{COMPONENT}}-main /tmp/{{COMPONENT}} && rm -rf /home/roboshop/{{COMPONENT}}/* && chown roboshop:roboshop /home/roboshop/{{COMPONENT}}
  ignore_errors: true 


- name: Copy files
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop   


- name: Setup python and install dependencies 
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /home/roboshop/{{COMPONENT}} 
  become_user: roboshop 

  
- name: Replace REDIS_ENDPOINT
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'REDIS_ENDPOINT'
    replace: '10.0.0.12'


- name: Replace MONGO_ENDPOINT/mongodb.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'MONGO_ENDPOINT'
    replace: 'mongodb.roboshop.internal'


- name: Replace CATALOGUE_ENDPOINT/catalogue.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'CATALOGUE_ENDPOINT'
    replace: 'catalogue.roboshop.internal'


- name: Replace MONGO_DNSNAME/mongodb.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: 'mongodb.roboshop.internal'



- name: Replace CARTENDPOINT/cart.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'CARTENDPOINT'
    replace: 'cart.roboshop.internal'

- name: Replace DBHOST/mysql.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'DBHOST'
    replace: 'mysql.roboshop.internal'

- name: Replace CARTHOST/cart.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'CARTHOST'
    replace: 'cart.roboshop.internal'

- name: Replace USERHOST/user.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'USERHOST'
    replace: 'user.roboshop.internal'

- name: Replace USERHOST/user.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'USERHOST'
    replace: 'user.roboshop.internal'

    
- name: Replace AMQPHOST/rabbitmq.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'AMQPHOST'
    replace: 'rabbitmq.roboshop.internal'


- name: Copy files
  ansible.builtin.copy:
    src: /home/roboshop/{{COMPONENT}}/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: yes


- name: Enable and start the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true    
    daemon_reload: yes    
