- name: Ensure SELinux is set to disabled mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
    
- name: Remove the Nginx package
  ansible.builtin.yum:
    name: nginx
    state: absent
  ignore_errors: true  

- name: Recursively remove directory
  ansible.builtin.file:
    path: /etc/nginx/*
    state: absent

- name: Install NGINX package
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true 
  ignore_errors: true  

- name: Download frontend files
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip


- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent


- name: Extract frontend.zip
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes


- name: Copy files
  ansible.builtin.copy:
    src: /usr/share/nginx/html/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes


- name: Copy file 
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/


- name: Enable and start the service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true    
    daemon_reload: yes

- name: adding the user node_exporter to install promethus agent 
  ansible.builtin.shell: useradd -M -r -s /bin/false node_exporter
  ignore_errors: true 

- name: Remove existing files and folders 
  ansible.builtin.file:
    path: 
      - /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
      - /tmp/node_exporter-1.5.0.linux-amd64
    state: absent
  ignore_errors: true  

- name: Remove existing file from usr-local-bin
  ansible.builtin.file:
    path: 
      - /usr/local/bin/node_exporter
    state: absent
  ignore_errors: true

- name: Remove existing file from etc
  ansible.builtin.file:
    path:
      - /etc/systemd/system/node_exporter
    state: absent
  ignore_errors: true


- name: Download node exporter files
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter to bin
  ansible.builtin.copy:
    src:  /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: node_exporter
    group: node_exporter
    mode: '0777'    
    remote_src: yes

- name: Copy systemd file. 
  ansible.builtin.copy:
    src:  /usr/local/bin/node_exporter
    dest: /etc/systemd/system/
    owner: node_exporter
    group: node_exporter
    mode: '0777' 
    remote_src: yes
    

- name: Enable and start the service
  ansible.builtin.systemd:
    name: /etc/systemd/system/node_exporter
    state: started
    enabled: true    
    daemon_reload: yes 
