- name: Ensure SELinux is set to disabled mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Download Rabbitmq repo on CentOS-8
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh

- name: Download erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh


- name: Install the  rabbitmq-server package
  ansible.builtin.yum:
    name: rabbitmq-server 
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true    
    daemon_reload: yes  


- name: Adding user to rabbitmq and setting the permissions
  community.rabbitmq.rabbitmq_user:
    user: "{{RABBITMQ_USER}}"
    password: "{{RABBITMQ_PASSWORD}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator

- name: adding the user node_exporter to install promethus agent 
  ansible.builtin.shell: useradd -M -r -s /bin/false node_exporter
  ignore_errors: true 

- name: Remove existing files and folders 
  ansible.builtin.file:
    path: 
      - /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
      - /tmp/node_exporter-1.5.0.linux-amd64
    state: absent
  ignore_errors: true  


- name: Download node exporter files
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter tp bin
  ansible.builtin.copy:
    src:  /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: node_exporter
    group: node_exporter
    mode: '0777'    
    remote_src: yes

- name: Copy systemd file. 
  ansible.builtin.copy:
    src:  node_exporter.service
    dest: /etc/systemd/system/
    

- name: Enable and start the service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true    
    daemon_reload: yes 
