- name: Ensure SELinux is set to disabled mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Remove the NODEJS package
  ansible.builtin.yum:
    name: nodejs
    state: absent


- name: Install the NODEJS package
  ansible.builtin.yum:
    name: nodejs
    state: present
  ignore_errors: true


- name: creating a roboshop user account 
  user:
    name: roboshop
  register: appuser
  ignore_errors: true 

- name: Download {{COMPONENT}} files
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/{{COMPONENT}}.zip

- name: Stop the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: stopped 
  ignore_errors: true    

- name: Recursively remove file
  ansible.builtin.file:
    path: /home/roboshop/*
    state: absent
    force: true

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /tmp/
    remote_src: yes

- name: Download NodeJS repo file and place it a directory
  ansible.builtin.shell: rm -rf /tmp/{{COMPONENT}} && mv /tmp/{{COMPONENT}}-main /tmp/{{COMPONENT}} && rm -rf /home/roboshop/{{COMPONENT}}/* && chown roboshop:roboshop /home/roboshop/{{COMPONENT}}
  ignore_errors: true 


- name: Copy files
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Install packages based on package.json.
  npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Replace CARTENDPOINT/cart.roboshop.internal
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/systemd.service
    regexp: 'CARTENDPOINT'
    replace: '10.0.0.6'

- name: Copy files
  ansible.builtin.copy:
    src: /home/roboshop/{{COMPONENT}}/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: yes


- name: Enable and start the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true    
    daemon_reload: yes 



